### ISSUE TITLE
singleton visualization when data has more than one value

### ISSUE THREAD

**Issue by gonzalezmorales** [UNStats/CountryProfiles#13]
When the preferred visualization is "singleton" BUT the data has more than one year, please pick the latest year, not the earliest one for the visualization. 

In the example below, the value displayed on the visualization should be "0.15% of GDP":

![image](https://user-images.githubusercontent.com/7047819/60616212-a3052c00-9dd9-11e9-8c98-e0735a70cc2b.png)

![image](https://user-images.githubusercontent.com/7047819/60616380-fe371e80-9dd9-11e9-89e5-5b788a147e9e.png)

**Comment by jpeterson** [comment]
@gonzalezmorales which country is the above sample for? I can only find "time_series" for all 9.5.1 indicators.

**Comment by gonzalezmorales** [comment]
@jpeterson :
This is another example from Tanzania:

![image](https://user-images.githubusercontent.com/7047819/60822418-676cb800-a173-11e9-9434-05d61a483175.png)

![image](https://user-images.githubusercontent.com/7047819/60822802-245f1480-a174-11e9-8d74-d12acca10595.png)
