### ISSUE TITLE
Country Maps

### ISSUE THREAD

**Issue by jpeterson** [UNStats/CountryProfiles#16]
We need to generate and display maps for each country.

**Comment by codylawson** [comment]
@gonzalezmorales As we discussed here's a comparison of the map with the firefly symbol alongside our current red dot. I feel the red dot is easier to see than the firefly but it's no problem to change the symbology. It will just take some time to regenerate the images, the update may not be ready until Monday if that's the case.

![symbology-comparison](https://user-images.githubusercontent.com/5149922/61148712-a31dbf80-a49c-11e9-8a60-2d7aa76ed2e0.png)

**Comment by gonzalezmorales** [comment]
@codylawson  - Thanks Cody.  Sorry for being picky, but is there a way to combine both approaches?  somethink like a red dot with a 'halo' effect?   Also, if the dot could be a couple of pixels bigger?

**Comment by gonzalezmorales** [comment]
(no problem is this needs to be rolled out later next week)

**Comment by codylawson** [comment]
@gonzalezmorales Something like this?

![SymbolExample](https://user-images.githubusercontent.com/5149922/61151199-9dc37380-a4a2-11e9-8c85-b65d108c1473.png)

**Comment by gonzalezmorales** [comment]
Yes looks good to me

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by codylawson** [comment]
Hi @gonzalezmorales. I reached out to our cartography team for some advice on symbology for the oceans basemap. They suggested something along these lines:

![SymbolExample_red](https://user-images.githubusercontent.com/5149922/61156975-0d8d2a80-a4b2-11e9-9f50-c639f9e56696.png)
![SymbolExample_blue](https://user-images.githubusercontent.com/5149922/61156805-8d66c500-a4b1-11e9-958f-9412b8262c46.png)

Would an option like either of these work for you?

**Comment by gonzalezmorales** [comment]
yes, totally fine.  I don't care that much about the color.  Maybe red makes it more visible?

**Comment by codylawson** [comment]
Agreed, red was my favorite as well.

**Comment by codylawson** [comment]
Resolved in #43
