### ISSUE TITLE
Use CV to determine y-axis range

### ISSUE THREAD

**Issue by jpeterson** [UNStats/CountryProfiles#18]
From Luis:

I think cases like the one shown below we need to have a rule to make the limits of the y axis wider, as the step in the series is only due to rounding.  We may need to look at something like the coefficient of variation
 
“The coefficient of variation (CV) is a statistical measure of the dispersion of data points in a data series around the mean. The coefficient of variation represents the ratio of the standard deviation to the mean, and it is a useful statistic for comparing the degree of variation from one data series to another, even if the means are drastically different from one another.”
 
When the CV is too small, we may need to treat the series in a way similar to a constant-value series, where the “padding” above the max and below the min is much larger.

https://country-profile-preview.netlify.com/bra#goal-3
![image](https://user-images.githubusercontent.com/3399064/60617691-7af1da80-9d91-11e9-8bad-7bd9fd714ae4.png)

**Comment by gonzalezmorales** [comment]
@jpeterson :  I included this logic in the generation of the "facts" and preferred visualization.  No need to do anything on the client side.
