### ISSUE TITLE
Side Panel nav does not update properly with scroll

### ISSUE THREAD

**Issue by apfister** [UNStats/CountryProfiles#29]
As the user scrolls down the page, the side nav for the goals is not highlighting the current section.

![60769502-3a96a300-a096-11e9-8d85-7a5e107a0282](https://user-images.githubusercontent.com/5233042/60769515-703b8c00-a096-11e9-95fb-ea241234a106.png)

**Comment by codylawson** [comment]
@apfister I'm not able to reproduce this issue. Can you provide more info on your browser and version, steps to reproduce etc. Thanks!

**Comment by apfister** [comment]
it's hard for me to reproduce consistently, but it did seem to happen after scrolling all the way down the page, then back up and then down again. after a few times of this, it went out of sync. this could be an edge case thing..

**Comment by codylawson** [comment]
Hey @apfister, have you seen this problem since you logged the issue? I'm wondering if we can close this now.

**Comment by apfister** [comment]
yeah i'll go ahead and close. thx.
