### ISSUE TITLE
old links to operations dashboards

### ISSUE THREAD

**Issue by apfister** [UNStats/CountryProfiles#33]
just to track this here..

 @gonzalezmorales is re-generating files with the latest ids for each OD.

**Comment by gonzalezmorales** [comment]
@apfister @jpeterson -
I updated the json files -- should have the right ids now:
https://github.com/UNStats/FIS4SDGs_New/tree/master/data/unsd/countryProfiles/output

**Comment by apfister** [comment]
i believe this is fixed. closing.
