### ISSUE TITLE
Fav Icon and title

### ISSUE THREAD

**Issue by gonzalezmorales** [UNStats/CountryProfiles#36]
Please change the fav icon to the sdg wheel, and change app title to "SDG Country Profiles" (plural)

![image](https://user-images.githubusercontent.com/7047819/60850633-306fc400-a1be-11e9-9298-548b8443b24f.png)

@codylawson - at this point "styling issues" are becoming top priority... will revert to "normal" after Wednesday :-)

**Comment by codylawson** [comment]
Resolved in #37

**Comment by codylawson** [comment]
@gonzalezmorales The favicon has been fixed since monday morning, but you may need to clear your cache and restart your browser to see the change.

**Comment by gonzalezmorales** [comment]
@codylawson Got it, thanks
