### ISSUE TITLE
Determine which links to use for Dashboards

### ISSUE THREAD

**Issue by jpeterson** [UNStats/CountryProfiles#6]
We need to implement the hyperlinks to Ops Dashboards, but are unsure where to find the links (or item ids).

**Comment by gonzalezmorales** [comment]
I'll add a dummy dashboard link for now - called 'hub-dashboard' -- will need to create the actual dashboards over the weekend(!)

**Comment by gonzalezmorales** [comment]
Done (with dummy dashboard version) - https://github.com/UNStats/FIS4SDGs_New/tree/master/data/unsd/countryProfiles/output

@apfister is looking into generation of dashboards for each series

**Comment by gonzalezmorales** [comment]
Done (with final dashboard references) - https://github.com/UNStats/FIS4SDGs_New/tree/master/data/unsd/countryProfiles/output

@jpeterson - this is ready to use for building the links to repositories and feature layers
