### ISSUE TITLE
Fix chart overflow when header string is too long.

### ISSUE THREAD

**Issue by gonzalezmorales** [UNStats/CountryProfiles#61]
![image](https://user-images.githubusercontent.com/7047819/93126481-63eb8f80-f69a-11ea-9e75-24fee85953fc.png)

When the header of a line chart is too long, the chart overflows to the right.  Need to allow for text wrapping into 2nd line?

**Comment by gonzalezmorales** [comment]
In addition, when the vertical axis lables have too many digits, they are truncated and not rendered.

**Comment by apfister** [comment]
@gonzalezmorales i think the first issue with sizing is pretty clear. for the truncated issue, should those values in the screen shot on the y-axis all have 1 decimal place? 

can you also paste in the link for that country so we can see it live?

**Comment by gonzalezmorales** [comment]
Sorry, the second issue was not really showing in the previous screen shot.  Here is one with the two issues present.
You can see it "live" here: https://country-profiles-git-exploreapp.unstats.vercel.app/https://country-profiles.unstatshub.org/ago

![image](https://user-images.githubusercontent.com/7047819/93145103-8e007a00-f6b9-11ea-8716-0b40e6affab0.png)

**Comment by gonzalezmorales** [comment]
Try Angola in https://country-profiles-git-exploreapp.unstats.vercel.app/  if the above link does not work

**Comment by gonzalezmorales** [comment]
Fixed
