### ISSUE TITLE
Albania fact missing text

### ISSUE THREAD

**Issue by jpeterson** [UNStats/CountryProfiles#8]
The `fact_text` for Albania indicator 17.18.3 is missing some text:

`As of <span class='fact-year'> 2018</span>, Albania.`

https://github.com/UNStats/FIS4SDGs_New/blob/master/data/unsd/countryProfiles/output/country_profile008.json#L2932

![image](https://user-images.githubusercontent.com/3399064/60606297-53424880-9d78-11e9-8803-e1d79c8e0528.png)

**Comment by gonzalezmorales** [comment]
The "fact builder" is failing when value is zero (see country codes 8, 52, 68...
going to take a look into it now

**Comment by gonzalezmorales** [comment]
This is done - please take new json files from https://github.com/UNStats/FIS4SDGs_New/tree/master/data/unsd/countryProfiles/output
